# Generated by Django 5.2.1 on 2025-05-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationGrossesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('mois_grossesse', models.IntegerField()),
                ('poids_kg', models.FloatField()),
                ('taille_cm', models.FloatField()),
                ('activité', models.CharField(max_length=20)),
                ('régime', models.CharField(max_length=20)),
                ('antécédents', models.CharField(max_length=50)),
                ('symptôme', models.CharField(max_length=30)),
                ('profil_risque', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
