# Configuration Fly.io pour le chatbot de grossesse
app = "chatbot-grossesse"
primary_region = "cdg"  # Paris

[build]
  dockerfile = "Dockerfile"

[env]
  DJANGO_SETTINGS_MODULE = "grossesse_bot.settings"
  DEBUG = "False"
  ALLOWED_HOSTS = ".fly.dev"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

